require "mixed_models/version"

require "mixed_models/matrix_methods.rb"
require "mixed_models/daru_methods.rb"
require "mixed_models/LMMData.rb"
require "mixed_models/Deviance.rb"
require "mixed_models/NelderMeadWithConstraints.rb"
require "mixed_models/LMM.rb"
require "mixed_models/ModelSpecification.rb"
require "mixed_models/LMMFormula.rb"
